export const responseMessage = {
  FETCH_DATA: 'Operation successfully Loaded',
  CREATED_DATA: 'Operation Successfully Created',
  UPDATED_DATA: 'Operation Successfully Updated',
  DELETED_DATA: 'Operation Successfully Deleted',
  NOT_FOUND: 'Data Not Found',
  WEAK_PASSWORD: 'Password is Weak',
  USERNAME_AVAILABLE: 'Username is Available',
  USERNAME_EXIST: 'Username Already Exists',
  EMAIL_EXIST: 'Email Id Already Exists',
  EMAIL_AVAILABLE: 'Email Id is Available',
  EXISTING_DATA: 'Data Already Exists',
  UNDO_DATA: 'Undo Successful',
  REPORT_GENERATED: 'Successfuly Signed-out',
  REPORT_DELIVERED: 'Report Sent Successfully',
  REMINEDER_SENT: 'Reminder Sent Successfully',
  REPORT_RESENT: 'Report Resent Successfully',
  FINAL_REPORT: 'Request a revision',
  ORDER_SUBMITTED: 'Your order is submitted.',
  REPORT_DELIVERED_ARCHIVED: 'Report Sent and Archived Successfully',
};